//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMaintenanceSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStockEntities : DbContext
    {
        public dbStockEntities()
            : base("name=dbStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblEquipmentStock> tblEquipmentStock { get; set; }
        public virtual DbSet<tblMaintenance> tblMaintenance { get; set; }
        public virtual DbSet<tblMaintnncEquipment> tblMaintnncEquipment { get; set; }
        public virtual DbSet<tblUsedObject> tblUsedObject { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
