//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMaintenanceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipmentStock
    {
        public int EquipmentID { get; set; }
        public string EquipmentCode { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentArea { get; set; }
        public string EquipmentBrand { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentSerialNumber { get; set; }
        public string EquipmentOrderCode { get; set; }
        public string EquipmentCompany { get; set; }
        public string EquipmentExtractedDate { get; set; }
        public string EquipmentAddedDate { get; set; }
        public string EquipmentCategory { get; set; }
        public string PurposeWhy { get; set; }
        public string EquipmentStockNumber { get; set; }
    }
}
