//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMaintenanceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaintenance
    {
        public int MaintenanceID { get; set; }
        public string StartingDate { get; set; }
        public string StartTime { get; set; }
        public string DueDate { get; set; }
        public string EndTime { get; set; }
        public string JobType { get; set; }
    }
}
